version: '3.8'
services:
  postgres-brewery-tour:
    container_name: postgres-brewery-tour
    image: postgres
    environment:
      POSTGRES_USER: dbbrewery
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: brewery-tour
      PGDATA: /data/postgres
    volumes:
      - postgres-softsec:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-brewery-tour: